### ISSUE TITLE
`Object#toString` is unreliable in ES6 environments

### ISSUE THREAD

**Issue by ljharb** [greaterjs/greaterjs#3]
Due to `Symbol.toStringTag`, `Object#toString` is no longer a reliable type checking mechanism.

You may wish to use the following packages to reliably detect builtin types:
- https://www.npmjs.com/package/is-boolean-object
- https://www.npmjs.com/package/is-callable
- https://www.npmjs.com/package/is-date-object
- https://www.npmjs.com/package/is-number-object
- https://www.npmjs.com/package/is-regex
- https://www.npmjs.com/package/is-string
- https://www.npmjs.com/package/is-symbol

**Comment by greaterjs** [comment]
Good idea and thanks for the contributions! Sorry for taking so long to get back to you. Some of the implementation was hastily done. I created the repo as a thought experiment: what if instead of forcing strict type safety (like === does), we made cross-type comparisons behave in practical or helpful ways. My thought is that programming might be more approachable to beginners and cause no problems for experts who prefer strict typing anyways.

That said, I see how this library might be useful, since JS doesn't offer a strict greater-than operator (>==). If there's ever strong interest in this kind of thing, I'll add cross-type behavior for `+`, `-`, `Math.foo` and whatever else too.

Thanks again, hope you're well!
